# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170929_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='teamimages/abc.jpg', upload_to='teamimages/'),
        ),
    ]
