# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_teammember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='teamimages/'),
        ),
    ]
